### PR TITLE
Todo list

### PR DESCRIPTION
**Pull request by ccobasi**
# This is a mini-project that allows you to

- Create new tasks for a to do list
- Display the current tasks in the todo list
- Modify an existing task
- Delete a task from the list

### CODE REVIEW

**Comment by rukundoeric** [comment]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - Follows gitwork-flow.  💯


- ### To Improve
  - [x] [MANDATORY] You did not follow project requirements. kindly, go back and read Project Specification carefully.
      - Interface ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
          - User can view all projects
          - User can view all to-dos in each project
          - User can edit the details of a to-do item
          - User can delete a to-do
      - Projects ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/todo-list))
          - The application allows to have different projects (or separate lists of to-dos)
          - There is a 'default' project
          - The user can create new projects
          - The user can assign a to-do list items to a project

  NOTE: Remember, the project should be created separately and be assigned to a task when creating it. what you currently have is that the project can only be created when creating a task.      

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Changes required❌.

# 👋 @ccobasi 

#### Good job on addressing the issues raised in the previous review, there is a default project, users can see all created projects and todos, however handling update and delete is not properly implemented😇.

* [x] After updating a project name we should not see it in the list. If we have 3 records and we update 1 we should still see three records in the list not four.

* [ ] Let enable the deletion of task and project name. With the exception of `default` users should be able to delete all `project` name.
* [x] Let us make the update button more obvious to the users, we can just place `update` text in the button

**[Optional]**
* [ ] Good job with the alert messages, it would be much better is the disappear after some time.
* [ ] I think it would be better to clear the form after task creation.
#### That is it, kindly make the changes and submit a re-review😎👨‍🔧

#### Happy coding 👨‍💻

Addo Forison

**Comment by ccobasi** [comment]
@Addo Forison

But I did not see deletion of projects on the project requirement

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @ccobasi**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] After creating a todo, I can't see the description or the note data.  Please make sure to fix them.
 

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 
Hello team @ccobasi 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇 

#### Highlights

- Your deployed app works correctly and the link is included in the README file ✔️ 
- You have worked on all changes requested by the previous TSE ✔️ 

With that, I approve of this project 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

**Pull request merged**
